/*
 * VirtoCommerce.SaaS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VirtoCloud.Client.Model;
using VirtoCloud.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VirtoCloud.Client.Test.Model
{
    /// <summary>
    ///  Class for testing HelmObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HelmObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HelmObject
        //private HelmObject instance;

        public HelmObjectTests()
        {
            // TODO uncomment below to create an instance of HelmObject
            //instance = new HelmObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HelmObject
        /// </summary>
        [Fact]
        public void HelmObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" HelmObject
            //Assert.IsType<HelmObject>(instance);
        }

        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Fact]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
    }
}
