// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// Description of all APIs
    /// </summary>
    public partial interface IArgoCDClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IAccountService.
        /// </summary>
        IAccountService AccountService { get; }

        /// <summary>
        /// Gets the IApplicationService.
        /// </summary>
        IApplicationService ApplicationService { get; }

        /// <summary>
        /// Gets the ICertificateService.
        /// </summary>
        ICertificateService CertificateService { get; }

        /// <summary>
        /// Gets the IClusterService.
        /// </summary>
        IClusterService ClusterService { get; }

        /// <summary>
        /// Gets the IGPGKeyService.
        /// </summary>
        IGPGKeyService GPGKeyService { get; }

        /// <summary>
        /// Gets the IProjectService.
        /// </summary>
        IProjectService ProjectService { get; }

        /// <summary>
        /// Gets the IRepoCredsService.
        /// </summary>
        IRepoCredsService RepoCredsService { get; }

        /// <summary>
        /// Gets the IRepositoryService.
        /// </summary>
        IRepositoryService RepositoryService { get; }

        /// <summary>
        /// Gets the ISessionService.
        /// </summary>
        ISessionService SessionService { get; }

        /// <summary>
        /// Gets the ISettingsService.
        /// </summary>
        ISettingsService SettingsService { get; }

        /// <summary>
        /// Gets the IVersionService.
        /// </summary>
        IVersionService VersionService { get; }

    }
}
