// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccountToken
    {
        /// <summary>
        /// Initializes a new instance of the AccountToken class.
        /// </summary>
        public AccountToken()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountToken class.
        /// </summary>
        public AccountToken(string expiresAt = default(string), string id = default(string), string issuedAt = default(string))
        {
            ExpiresAt = expiresAt;
            Id = id;
            IssuedAt = issuedAt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expiresAt")]
        public string ExpiresAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "issuedAt")]
        public string IssuedAt { get; set; }

    }
}
