// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AccountAccount
    {
        /// <summary>
        /// Initializes a new instance of the AccountAccount class.
        /// </summary>
        public AccountAccount()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountAccount class.
        /// </summary>
        public AccountAccount(IList<string> capabilities = default(IList<string>), bool? enabled = default(bool?), string name = default(string), IList<AccountToken> tokens = default(IList<AccountToken>))
        {
            Capabilities = capabilities;
            Enabled = enabled;
            Name = name;
            Tokens = tokens;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capabilities")]
        public IList<string> Capabilities { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "enabled")]
        public bool? Enabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokens")]
        public IList<AccountToken> Tokens { get; set; }

    }
}
