// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccountUpdatePasswordRequest
    {
        /// <summary>
        /// Initializes a new instance of the AccountUpdatePasswordRequest
        /// class.
        /// </summary>
        public AccountUpdatePasswordRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountUpdatePasswordRequest
        /// class.
        /// </summary>
        public AccountUpdatePasswordRequest(string currentPassword = default(string), string name = default(string), string newPassword = default(string))
        {
            CurrentPassword = currentPassword;
            Name = name;
            NewPassword = newPassword;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currentPassword")]
        public string CurrentPassword { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "newPassword")]
        public string NewPassword { get; set; }

    }
}
