// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AccountAccountsList
    {
        /// <summary>
        /// Initializes a new instance of the AccountAccountsList class.
        /// </summary>
        public AccountAccountsList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountAccountsList class.
        /// </summary>
        public AccountAccountsList(IList<AccountAccount> items = default(IList<AccountAccount>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<AccountAccount> Items { get; set; }

    }
}
