// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ApplicationSyncRequest is a request to apply the config state to live
    /// state
    /// </summary>
    public partial class ApplicationApplicationSyncRequest
    {
        /// <summary>
        /// Initializes a new instance of the ApplicationApplicationSyncRequest
        /// class.
        /// </summary>
        public ApplicationApplicationSyncRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApplicationApplicationSyncRequest
        /// class.
        /// </summary>
        public ApplicationApplicationSyncRequest(bool? dryRun = default(bool?), IList<V1alpha1Info> infos = default(IList<V1alpha1Info>), IList<string> manifests = default(IList<string>), string name = default(string), bool? prune = default(bool?), IList<V1alpha1SyncOperationResource> resources = default(IList<V1alpha1SyncOperationResource>), V1alpha1RetryStrategy retryStrategy = default(V1alpha1RetryStrategy), string revision = default(string), V1alpha1SyncStrategy strategy = default(V1alpha1SyncStrategy), ApplicationSyncOptions syncOptions = default(ApplicationSyncOptions))
        {
            DryRun = dryRun;
            Infos = infos;
            Manifests = manifests;
            Name = name;
            Prune = prune;
            Resources = resources;
            RetryStrategy = retryStrategy;
            Revision = revision;
            Strategy = strategy;
            SyncOptions = syncOptions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dryRun")]
        public bool? DryRun { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "infos")]
        public IList<V1alpha1Info> Infos { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "manifests")]
        public IList<string> Manifests { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "prune")]
        public bool? Prune { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resources")]
        public IList<V1alpha1SyncOperationResource> Resources { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "retryStrategy")]
        public V1alpha1RetryStrategy RetryStrategy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "revision")]
        public string Revision { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "strategy")]
        public V1alpha1SyncStrategy Strategy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "syncOptions")]
        public ApplicationSyncOptions SyncOptions { get; set; }

    }
}
