// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClusterOIDCConfig
    {
        /// <summary>
        /// Initializes a new instance of the ClusterOIDCConfig class.
        /// </summary>
        public ClusterOIDCConfig()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClusterOIDCConfig class.
        /// </summary>
        public ClusterOIDCConfig(string cliClientID = default(string), string clientID = default(string), IDictionary<string, OidcClaim> idTokenClaims = default(IDictionary<string, OidcClaim>), string issuer = default(string), string name = default(string), IList<string> scopes = default(IList<string>))
        {
            CliClientID = cliClientID;
            ClientID = clientID;
            IdTokenClaims = idTokenClaims;
            Issuer = issuer;
            Name = name;
            Scopes = scopes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cliClientID")]
        public string CliClientID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientID")]
        public string ClientID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idTokenClaims")]
        public IDictionary<string, OidcClaim> IdTokenClaims { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "issuer")]
        public string Issuer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "scopes")]
        public IList<string> Scopes { get; set; }

    }
}
