// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Help settings
    /// </summary>
    public partial class ClusterHelp
    {
        /// <summary>
        /// Initializes a new instance of the ClusterHelp class.
        /// </summary>
        public ClusterHelp()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClusterHelp class.
        /// </summary>
        /// <param name="chatText">the text for getting chat help, defaults to
        /// "Chat now!"</param>
        /// <param name="chatUrl">the URL for getting chat help, this will
        /// typically be your Slack channel for support</param>
        public ClusterHelp(string chatText = default(string), string chatUrl = default(string))
        {
            ChatText = chatText;
            ChatUrl = chatUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the text for getting chat help, defaults to "Chat
        /// now!"
        /// </summary>
        [JsonProperty(PropertyName = "chatText")]
        public string ChatText { get; set; }

        /// <summary>
        /// Gets or sets the URL for getting chat help, this will typically be
        /// your Slack channel for support
        /// </summary>
        [JsonProperty(PropertyName = "chatUrl")]
        public string ChatUrl { get; set; }

    }
}
