// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClusterSettings
    {
        /// <summary>
        /// Initializes a new instance of the ClusterSettings class.
        /// </summary>
        public ClusterSettings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClusterSettings class.
        /// </summary>
        public ClusterSettings(string appLabelKey = default(string), IList<V1alpha1ConfigManagementPlugin> configManagementPlugins = default(IList<V1alpha1ConfigManagementPlugin>), ClusterDexConfig dexConfig = default(ClusterDexConfig), ClusterGoogleAnalyticsConfig googleAnalytics = default(ClusterGoogleAnalyticsConfig), ClusterHelp help = default(ClusterHelp), V1alpha1KustomizeOptions kustomizeOptions = default(V1alpha1KustomizeOptions), IList<string> kustomizeVersions = default(IList<string>), ClusterOIDCConfig oidcConfig = default(ClusterOIDCConfig), IList<ClusterPlugin> plugins = default(IList<ClusterPlugin>), IDictionary<string, V1alpha1ResourceOverride> resourceOverrides = default(IDictionary<string, V1alpha1ResourceOverride>), bool? statusBadgeEnabled = default(bool?), string uiBannerContent = default(string), string uiBannerURL = default(string), string uiCssURL = default(string), string url = default(string), bool? userLoginsDisabled = default(bool?))
        {
            AppLabelKey = appLabelKey;
            ConfigManagementPlugins = configManagementPlugins;
            DexConfig = dexConfig;
            GoogleAnalytics = googleAnalytics;
            Help = help;
            KustomizeOptions = kustomizeOptions;
            KustomizeVersions = kustomizeVersions;
            OidcConfig = oidcConfig;
            Plugins = plugins;
            ResourceOverrides = resourceOverrides;
            StatusBadgeEnabled = statusBadgeEnabled;
            UiBannerContent = uiBannerContent;
            UiBannerURL = uiBannerURL;
            UiCssURL = uiCssURL;
            Url = url;
            UserLoginsDisabled = userLoginsDisabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appLabelKey")]
        public string AppLabelKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "configManagementPlugins")]
        public IList<V1alpha1ConfigManagementPlugin> ConfigManagementPlugins { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dexConfig")]
        public ClusterDexConfig DexConfig { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "googleAnalytics")]
        public ClusterGoogleAnalyticsConfig GoogleAnalytics { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "help")]
        public ClusterHelp Help { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "kustomizeOptions")]
        public V1alpha1KustomizeOptions KustomizeOptions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "kustomizeVersions")]
        public IList<string> KustomizeVersions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "oidcConfig")]
        public ClusterOIDCConfig OidcConfig { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "plugins")]
        public IList<ClusterPlugin> Plugins { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceOverrides")]
        public IDictionary<string, V1alpha1ResourceOverride> ResourceOverrides { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statusBadgeEnabled")]
        public bool? StatusBadgeEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uiBannerContent")]
        public string UiBannerContent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uiBannerURL")]
        public string UiBannerURL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uiCssURL")]
        public string UiCssURL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userLoginsDisabled")]
        public bool? UserLoginsDisabled { get; set; }

    }
}
