// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Response to a public key creation request
    /// </summary>
    public partial class GpgkeyGnuPGPublicKeyCreateResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GpgkeyGnuPGPublicKeyCreateResponse class.
        /// </summary>
        public GpgkeyGnuPGPublicKeyCreateResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// GpgkeyGnuPGPublicKeyCreateResponse class.
        /// </summary>
        /// <param name="skipped">List of key IDs that haven been skipped
        /// because they already exist on the server</param>
        public GpgkeyGnuPGPublicKeyCreateResponse(V1alpha1GnuPGPublicKeyList created = default(V1alpha1GnuPGPublicKeyList), IList<string> skipped = default(IList<string>))
        {
            Created = created;
            Skipped = skipped;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public V1alpha1GnuPGPublicKeyList Created { get; set; }

        /// <summary>
        /// Gets or sets list of key IDs that haven been skipped because they
        /// already exist on the server
        /// </summary>
        [JsonProperty(PropertyName = "skipped")]
        public IList<string> Skipped { get; set; }

    }
}
