// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OidcClaim
    {
        /// <summary>
        /// Initializes a new instance of the OidcClaim class.
        /// </summary>
        public OidcClaim()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OidcClaim class.
        /// </summary>
        public OidcClaim(bool? essential = default(bool?), string value = default(string), IList<string> values = default(IList<string>))
        {
            Essential = essential;
            Value = value;
            Values = values;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "essential")]
        public bool? Essential { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "values")]
        public IList<string> Values { get; set; }

    }
}
