// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProjectProjectUpdateRequest
    {
        /// <summary>
        /// Initializes a new instance of the ProjectProjectUpdateRequest
        /// class.
        /// </summary>
        public ProjectProjectUpdateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProjectProjectUpdateRequest
        /// class.
        /// </summary>
        public ProjectProjectUpdateRequest(V1alpha1AppProject project = default(V1alpha1AppProject))
        {
            Project = project;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public V1alpha1AppProject Project { get; set; }

    }
}
