// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProjectGlobalProjectsResponse
    {
        /// <summary>
        /// Initializes a new instance of the ProjectGlobalProjectsResponse
        /// class.
        /// </summary>
        public ProjectGlobalProjectsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProjectGlobalProjectsResponse
        /// class.
        /// </summary>
        public ProjectGlobalProjectsResponse(IList<V1alpha1AppProject> items = default(IList<V1alpha1AppProject>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<V1alpha1AppProject> Items { get; set; }

    }
}
