// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ProjectCreateRequest defines project creation parameters.
    /// </summary>
    public partial class ProjectProjectCreateRequest
    {
        /// <summary>
        /// Initializes a new instance of the ProjectProjectCreateRequest
        /// class.
        /// </summary>
        public ProjectProjectCreateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProjectProjectCreateRequest
        /// class.
        /// </summary>
        public ProjectProjectCreateRequest(V1alpha1AppProject project = default(V1alpha1AppProject), bool? upsert = default(bool?))
        {
            Project = project;
            Upsert = upsert;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public V1alpha1AppProject Project { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "upsert")]
        public bool? Upsert { get; set; }

    }
}
