// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProtobufAny
    {
        /// <summary>
        /// Initializes a new instance of the ProtobufAny class.
        /// </summary>
        public ProtobufAny()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProtobufAny class.
        /// </summary>
        public ProtobufAny(string typeUrl = default(string), byte[] value = default(byte[]))
        {
            TypeUrl = typeUrl;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type_url")]
        public string TypeUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public byte[] Value { get; set; }

    }
}
