// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RepositoryKsonnetEnvironmentDestination
    {
        /// <summary>
        /// Initializes a new instance of the
        /// RepositoryKsonnetEnvironmentDestination class.
        /// </summary>
        public RepositoryKsonnetEnvironmentDestination()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// RepositoryKsonnetEnvironmentDestination class.
        /// </summary>
        /// <param name="namespaceProperty">Namespace is the namespace of the
        /// Kubernetes server that targets should be deployed to</param>
        /// <param name="server">Server is the Kubernetes server that the
        /// cluster is running on.</param>
        public RepositoryKsonnetEnvironmentDestination(string namespaceProperty = default(string), string server = default(string))
        {
            NamespaceProperty = namespaceProperty;
            Server = server;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets namespace is the namespace of the Kubernetes server
        /// that targets should be deployed to
        /// </summary>
        [JsonProperty(PropertyName = "namespace")]
        public string NamespaceProperty { get; set; }

        /// <summary>
        /// Gets or sets server is the Kubernetes server that the cluster is
        /// running on.
        /// </summary>
        [JsonProperty(PropertyName = "server")]
        public string Server { get; set; }

    }
}
