// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// RepoAppDetailsQuery contains query information for app details request
    /// </summary>
    public partial class RepositoryRepoAppDetailsQuery
    {
        /// <summary>
        /// Initializes a new instance of the RepositoryRepoAppDetailsQuery
        /// class.
        /// </summary>
        public RepositoryRepoAppDetailsQuery()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RepositoryRepoAppDetailsQuery
        /// class.
        /// </summary>
        public RepositoryRepoAppDetailsQuery(string appName = default(string), V1alpha1ApplicationSource source = default(V1alpha1ApplicationSource))
        {
            AppName = appName;
            Source = source;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appName")]
        public string AppName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public V1alpha1ApplicationSource Source { get; set; }

    }
}
