// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// AppInfo contains application type and app file path
    /// </summary>
    public partial class RepositoryAppInfo
    {
        /// <summary>
        /// Initializes a new instance of the RepositoryAppInfo class.
        /// </summary>
        public RepositoryAppInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RepositoryAppInfo class.
        /// </summary>
        public RepositoryAppInfo(string path = default(string), string type = default(string))
        {
            Path = path;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
