// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// HelmAppSpec contains helm app name  in source repo
    /// </summary>
    public partial class RepositoryHelmAppSpec
    {
        /// <summary>
        /// Initializes a new instance of the RepositoryHelmAppSpec class.
        /// </summary>
        public RepositoryHelmAppSpec()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RepositoryHelmAppSpec class.
        /// </summary>
        /// <param name="fileParameters">helm file parameters</param>
        /// <param name="parameters">the output of `helm inspect
        /// values`</param>
        /// <param name="values">the contents of values.yaml</param>
        public RepositoryHelmAppSpec(IList<V1alpha1HelmFileParameter> fileParameters = default(IList<V1alpha1HelmFileParameter>), string name = default(string), IList<V1alpha1HelmParameter> parameters = default(IList<V1alpha1HelmParameter>), IList<string> valueFiles = default(IList<string>), string values = default(string))
        {
            FileParameters = fileParameters;
            Name = name;
            Parameters = parameters;
            ValueFiles = valueFiles;
            Values = values;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets helm file parameters
        /// </summary>
        [JsonProperty(PropertyName = "fileParameters")]
        public IList<V1alpha1HelmFileParameter> FileParameters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the output of `helm inspect values`
        /// </summary>
        [JsonProperty(PropertyName = "parameters")]
        public IList<V1alpha1HelmParameter> Parameters { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "valueFiles")]
        public IList<string> ValueFiles { get; set; }

        /// <summary>
        /// Gets or sets the contents of values.yaml
        /// </summary>
        [JsonProperty(PropertyName = "values")]
        public string Values { get; set; }

    }
}
