// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RepositoryManifestResponse
    {
        /// <summary>
        /// Initializes a new instance of the RepositoryManifestResponse class.
        /// </summary>
        public RepositoryManifestResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RepositoryManifestResponse class.
        /// </summary>
        /// <param name="revision">resolved revision</param>
        /// <param name="verifyResult">Raw response of git verify-commit
        /// operation (always the empty string for Helm)</param>
        public RepositoryManifestResponse(IList<string> manifests = default(IList<string>), string namespaceProperty = default(string), string revision = default(string), string server = default(string), string sourceType = default(string), string verifyResult = default(string))
        {
            Manifests = manifests;
            NamespaceProperty = namespaceProperty;
            Revision = revision;
            Server = server;
            SourceType = sourceType;
            VerifyResult = verifyResult;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "manifests")]
        public IList<string> Manifests { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "namespace")]
        public string NamespaceProperty { get; set; }

        /// <summary>
        /// Gets or sets resolved revision
        /// </summary>
        [JsonProperty(PropertyName = "revision")]
        public string Revision { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "server")]
        public string Server { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceType")]
        public string SourceType { get; set; }

        /// <summary>
        /// Gets or sets raw response of git verify-commit operation (always
        /// the empty string for Helm)
        /// </summary>
        [JsonProperty(PropertyName = "verifyResult")]
        public string VerifyResult { get; set; }

    }
}
