// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// KustomizeAppSpec contains kustomize images
    /// </summary>
    public partial class RepositoryKustomizeAppSpec
    {
        /// <summary>
        /// Initializes a new instance of the RepositoryKustomizeAppSpec class.
        /// </summary>
        public RepositoryKustomizeAppSpec()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RepositoryKustomizeAppSpec class.
        /// </summary>
        /// <param name="images">images is a list of available images.</param>
        public RepositoryKustomizeAppSpec(IList<string> images = default(IList<string>))
        {
            Images = images;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets images is a list of available images.
        /// </summary>
        [JsonProperty(PropertyName = "images")]
        public IList<string> Images { get; set; }

    }
}
