// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The current user's userInfo info
    /// </summary>
    public partial class SessionGetUserInfoResponse
    {
        /// <summary>
        /// Initializes a new instance of the SessionGetUserInfoResponse class.
        /// </summary>
        public SessionGetUserInfoResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SessionGetUserInfoResponse class.
        /// </summary>
        public SessionGetUserInfoResponse(IList<string> groups = default(IList<string>), string iss = default(string), bool? loggedIn = default(bool?), string username = default(string))
        {
            Groups = groups;
            Iss = iss;
            LoggedIn = loggedIn;
            Username = username;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groups")]
        public IList<string> Groups { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "iss")]
        public string Iss { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "loggedIn")]
        public bool? LoggedIn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

    }
}
