// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// TODO: describe this type
    /// </summary>
    public partial class V1alpha1HostResourceInfo
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1HostResourceInfo class.
        /// </summary>
        public V1alpha1HostResourceInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1HostResourceInfo class.
        /// </summary>
        public V1alpha1HostResourceInfo(string capacity = default(string), string requestedByApp = default(string), string requestedByNeighbors = default(string), string resourceName = default(string))
        {
            Capacity = capacity;
            RequestedByApp = requestedByApp;
            RequestedByNeighbors = requestedByNeighbors;
            ResourceName = resourceName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capacity")]
        public string Capacity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestedByApp")]
        public string RequestedByApp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestedByNeighbors")]
        public string RequestedByNeighbors { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceName")]
        public string ResourceName { get; set; }

    }
}
