// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Command holds binary path and arguments list
    /// </summary>
    public partial class V1alpha1Command
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1Command class.
        /// </summary>
        public V1alpha1Command()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1Command class.
        /// </summary>
        public V1alpha1Command(IList<string> args = default(IList<string>), IList<string> command = default(IList<string>))
        {
            Args = args;
            Command = command;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "args")]
        public IList<string> Args { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "command")]
        public IList<string> Command { get; set; }

    }
}
