// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ConfigManagementPlugin contains config management plugin configuration
    /// </summary>
    public partial class V1alpha1ConfigManagementPlugin
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1ConfigManagementPlugin
        /// class.
        /// </summary>
        public V1alpha1ConfigManagementPlugin()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1ConfigManagementPlugin
        /// class.
        /// </summary>
        public V1alpha1ConfigManagementPlugin(V1alpha1Command generate = default(V1alpha1Command), V1alpha1Command init = default(V1alpha1Command), string name = default(string))
        {
            Generate = generate;
            Init = init;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "generate")]
        public V1alpha1Command Generate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "init")]
        public V1alpha1Command Init { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
