// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Operation contains information about a requested or running operation
    /// </summary>
    public partial class V1alpha1Operation
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1Operation class.
        /// </summary>
        public V1alpha1Operation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1Operation class.
        /// </summary>
        /// <param name="info">Info is a list of informational items for this
        /// operation</param>
        public V1alpha1Operation(IList<V1alpha1Info> info = default(IList<V1alpha1Info>), V1alpha1OperationInitiator initiatedBy = default(V1alpha1OperationInitiator), V1alpha1RetryStrategy retry = default(V1alpha1RetryStrategy), V1alpha1SyncOperation sync = default(V1alpha1SyncOperation))
        {
            Info = info;
            InitiatedBy = initiatedBy;
            Retry = retry;
            Sync = sync;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets info is a list of informational items for this
        /// operation
        /// </summary>
        [JsonProperty(PropertyName = "info")]
        public IList<V1alpha1Info> Info { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "initiatedBy")]
        public V1alpha1OperationInitiator InitiatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "retry")]
        public V1alpha1RetryStrategy Retry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sync")]
        public V1alpha1SyncOperation Sync { get; set; }

    }
}
