// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ApplicationTree holds nodes which belongs to the application
    /// TODO: describe purpose of this type
    /// </summary>
    public partial class V1alpha1ApplicationTree
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1ApplicationTree class.
        /// </summary>
        public V1alpha1ApplicationTree()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1ApplicationTree class.
        /// </summary>
        /// <param name="hosts">Hosts holds list of Kubernetes nodes that run
        /// application related pods</param>
        /// <param name="nodes">Nodes contains list of nodes which either
        /// directly managed by the application and children of directly
        /// managed nodes.</param>
        /// <param name="orphanedNodes">OrphanedNodes contains if or orphaned
        /// nodes: nodes which are not managed by the app but in the same
        /// namespace. List is populated only if orphaned resources enabled in
        /// app project.</param>
        public V1alpha1ApplicationTree(IList<V1alpha1HostInfo> hosts = default(IList<V1alpha1HostInfo>), IList<V1alpha1ResourceNode> nodes = default(IList<V1alpha1ResourceNode>), IList<V1alpha1ResourceNode> orphanedNodes = default(IList<V1alpha1ResourceNode>))
        {
            Hosts = hosts;
            Nodes = nodes;
            OrphanedNodes = orphanedNodes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets hosts holds list of Kubernetes nodes that run
        /// application related pods
        /// </summary>
        [JsonProperty(PropertyName = "hosts")]
        public IList<V1alpha1HostInfo> Hosts { get; set; }

        /// <summary>
        /// Gets or sets nodes contains list of nodes which either directly
        /// managed by the application and children of directly managed nodes.
        /// </summary>
        [JsonProperty(PropertyName = "nodes")]
        public IList<V1alpha1ResourceNode> Nodes { get; set; }

        /// <summary>
        /// Gets or sets orphanedNodes contains if or orphaned nodes: nodes
        /// which are not managed by the app but in the same namespace. List is
        /// populated only if orphaned resources enabled in app project.
        /// </summary>
        [JsonProperty(PropertyName = "orphanedNodes")]
        public IList<V1alpha1ResourceNode> OrphanedNodes { get; set; }

    }
}
