// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// SignatureKey is the specification of a key required to verify commit
    /// signatures with
    /// </summary>
    public partial class V1alpha1SignatureKey
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1SignatureKey class.
        /// </summary>
        public V1alpha1SignatureKey()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1SignatureKey class.
        /// </summary>
        /// <param name="keyID">The ID of the key in hexadecimal
        /// notation</param>
        public V1alpha1SignatureKey(string keyID = default(string))
        {
            KeyID = keyID;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the ID of the key in hexadecimal notation
        /// </summary>
        [JsonProperty(PropertyName = "keyID")]
        public string KeyID { get; set; }

    }
}
