// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ClusterList is a collection of Clusters.
    /// </summary>
    public partial class V1alpha1ClusterList
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1ClusterList class.
        /// </summary>
        public V1alpha1ClusterList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1ClusterList class.
        /// </summary>
        public V1alpha1ClusterList(IList<V1alpha1Cluster> items = default(IList<V1alpha1Cluster>), V1ListMeta metadata = default(V1ListMeta))
        {
            Items = items;
            Metadata = metadata;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<V1alpha1Cluster> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metadata")]
        public V1ListMeta Metadata { get; set; }

    }
}
