// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// KustomizeOptions are options for kustomize to use when building
    /// manifests
    /// </summary>
    public partial class V1alpha1KustomizeOptions
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1KustomizeOptions class.
        /// </summary>
        public V1alpha1KustomizeOptions()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1KustomizeOptions class.
        /// </summary>
        /// <param name="binaryPath">BinaryPath holds optional path to
        /// kustomize binary</param>
        /// <param name="buildOptions">BuildOptions is a string of build
        /// parameters to use when calling `kustomize build`</param>
        public V1alpha1KustomizeOptions(string binaryPath = default(string), string buildOptions = default(string))
        {
            BinaryPath = binaryPath;
            BuildOptions = buildOptions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets binaryPath holds optional path to kustomize binary
        /// </summary>
        [JsonProperty(PropertyName = "binaryPath")]
        public string BinaryPath { get; set; }

        /// <summary>
        /// Gets or sets buildOptions is a string of build parameters to use
        /// when calling `kustomize build`
        /// </summary>
        [JsonProperty(PropertyName = "buildOptions")]
        public string BuildOptions { get; set; }

    }
}
