// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ApplicationSource contains all required information about the source of
    /// an application
    /// </summary>
    public partial class V1alpha1ApplicationSource
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1ApplicationSource class.
        /// </summary>
        public V1alpha1ApplicationSource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1ApplicationSource class.
        /// </summary>
        /// <param name="chart">Chart is a Helm chart name, and must be
        /// specified for applications sourced from a Helm repo.</param>
        /// <param name="path">Path is a directory path within the Git
        /// repository, and is only valid for applications sourced from
        /// Git.</param>
        /// <param name="repoURL">RepoURL is the URL to the repository (Git or
        /// Helm) that contains the application manifests</param>
        /// <param name="targetRevision">TargetRevision defines the revision of
        /// the source to sync the application to.
        /// In case of Git, this can be commit, tag, or branch. If omitted,
        /// will equal to HEAD.
        /// In case of Helm, this is a semver tag for the Chart's
        /// version.</param>
        public V1alpha1ApplicationSource(string chart = default(string), V1alpha1ApplicationSourceDirectory directory = default(V1alpha1ApplicationSourceDirectory), V1alpha1ApplicationSourceHelm helm = default(V1alpha1ApplicationSourceHelm), V1alpha1ApplicationSourceKsonnet ksonnet = default(V1alpha1ApplicationSourceKsonnet), V1alpha1ApplicationSourceKustomize kustomize = default(V1alpha1ApplicationSourceKustomize), string path = default(string), V1alpha1ApplicationSourcePlugin plugin = default(V1alpha1ApplicationSourcePlugin), string repoURL = default(string), string targetRevision = default(string))
        {
            Chart = chart;
            Directory = directory;
            Helm = helm;
            Ksonnet = ksonnet;
            Kustomize = kustomize;
            Path = path;
            Plugin = plugin;
            RepoURL = repoURL;
            TargetRevision = targetRevision;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets chart is a Helm chart name, and must be specified for
        /// applications sourced from a Helm repo.
        /// </summary>
        [JsonProperty(PropertyName = "chart")]
        public string Chart { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "directory")]
        public V1alpha1ApplicationSourceDirectory Directory { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "helm")]
        public V1alpha1ApplicationSourceHelm Helm { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ksonnet")]
        public V1alpha1ApplicationSourceKsonnet Ksonnet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "kustomize")]
        public V1alpha1ApplicationSourceKustomize Kustomize { get; set; }

        /// <summary>
        /// Gets or sets path is a directory path within the Git repository,
        /// and is only valid for applications sourced from Git.
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "plugin")]
        public V1alpha1ApplicationSourcePlugin Plugin { get; set; }

        /// <summary>
        /// Gets or sets repoURL is the URL to the repository (Git or Helm)
        /// that contains the application manifests
        /// </summary>
        [JsonProperty(PropertyName = "repoURL")]
        public string RepoURL { get; set; }

        /// <summary>
        /// Gets or sets targetRevision defines the revision of the source to
        /// sync the application to.
        /// In case of Git, this can be commit, tag, or branch. If omitted,
        /// will equal to HEAD.
        /// In case of Helm, this is a semver tag for the Chart's version.
        /// </summary>
        [JsonProperty(PropertyName = "targetRevision")]
        public string TargetRevision { get; set; }

    }
}
