// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ResourceOverride holds configuration to customize resource diffing and
    /// health assessment
    /// TODO: describe the members of this type
    /// </summary>
    public partial class V1alpha1ResourceOverride
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1ResourceOverride class.
        /// </summary>
        public V1alpha1ResourceOverride()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1ResourceOverride class.
        /// </summary>
        public V1alpha1ResourceOverride(string actions = default(string), string healthLua = default(string), V1alpha1OverrideIgnoreDiff ignoreDifferences = default(V1alpha1OverrideIgnoreDiff), IList<V1alpha1KnownTypeField> knownTypeFields = default(IList<V1alpha1KnownTypeField>))
        {
            Actions = actions;
            HealthLua = healthLua;
            IgnoreDifferences = ignoreDifferences;
            KnownTypeFields = knownTypeFields;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "actions")]
        public string Actions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "healthLua")]
        public string HealthLua { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ignoreDifferences")]
        public V1alpha1OverrideIgnoreDiff IgnoreDifferences { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "knownTypeFields")]
        public IList<V1alpha1KnownTypeField> KnownTypeFields { get; set; }

    }
}
