// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ResourceNode contains information about live resource and its children
    /// TODO: describe members of this type
    /// </summary>
    public partial class V1alpha1ResourceNode
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1ResourceNode class.
        /// </summary>
        public V1alpha1ResourceNode()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1ResourceNode class.
        /// </summary>
        public V1alpha1ResourceNode(V1Time createdAt = default(V1Time), V1alpha1HealthStatus health = default(V1alpha1HealthStatus), IList<string> images = default(IList<string>), IList<V1alpha1InfoItem> info = default(IList<V1alpha1InfoItem>), V1alpha1ResourceNetworkingInfo networkingInfo = default(V1alpha1ResourceNetworkingInfo), IList<V1alpha1ResourceRef> parentRefs = default(IList<V1alpha1ResourceRef>), V1alpha1ResourceRef resourceRef = default(V1alpha1ResourceRef), string resourceVersion = default(string))
        {
            CreatedAt = createdAt;
            Health = health;
            Images = images;
            Info = info;
            NetworkingInfo = networkingInfo;
            ParentRefs = parentRefs;
            ResourceRef = resourceRef;
            ResourceVersion = resourceVersion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdAt")]
        public V1Time CreatedAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "health")]
        public V1alpha1HealthStatus Health { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "images")]
        public IList<string> Images { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "info")]
        public IList<V1alpha1InfoItem> Info { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "networkingInfo")]
        public V1alpha1ResourceNetworkingInfo NetworkingInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentRefs")]
        public IList<V1alpha1ResourceRef> ParentRefs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceRef")]
        public V1alpha1ResourceRef ResourceRef { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceVersion")]
        public string ResourceVersion { get; set; }

    }
}
