// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ConnectionState contains information about remote resource connection
    /// state, currently used for clusters and repositories
    /// </summary>
    public partial class V1alpha1ConnectionState
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1ConnectionState class.
        /// </summary>
        public V1alpha1ConnectionState()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1ConnectionState class.
        /// </summary>
        /// <param name="message">Message contains human readable information
        /// about the connection status</param>
        /// <param name="status">Status contains the current status indicator
        /// for the connection</param>
        public V1alpha1ConnectionState(V1Time attemptedAt = default(V1Time), string message = default(string), string status = default(string))
        {
            AttemptedAt = attemptedAt;
            Message = message;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attemptedAt")]
        public V1Time AttemptedAt { get; set; }

        /// <summary>
        /// Gets or sets message contains human readable information about the
        /// connection status
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets status contains the current status indicator for the
        /// connection
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
