// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// AppProjectList is list of AppProject resources
    /// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
    /// </summary>
    public partial class V1alpha1AppProjectList
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1AppProjectList class.
        /// </summary>
        public V1alpha1AppProjectList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1AppProjectList class.
        /// </summary>
        public V1alpha1AppProjectList(IList<V1alpha1AppProject> items = default(IList<V1alpha1AppProject>), V1ListMeta metadata = default(V1ListMeta))
        {
            Items = items;
            Metadata = metadata;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<V1alpha1AppProject> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metadata")]
        public V1ListMeta Metadata { get; set; }

    }
}
