// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// JsonnetVar represents a variable to be passed to jsonnet during
    /// manifest generation
    /// </summary>
    public partial class V1alpha1JsonnetVar
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1JsonnetVar class.
        /// </summary>
        public V1alpha1JsonnetVar()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1JsonnetVar class.
        /// </summary>
        public V1alpha1JsonnetVar(bool? code = default(bool?), string name = default(string), string value = default(string))
        {
            Code = code;
            Name = name;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public bool? Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
