// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// SyncStatus contains information about the currently observed live and
    /// desired states of an application
    /// </summary>
    public partial class V1alpha1SyncStatus
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1SyncStatus class.
        /// </summary>
        public V1alpha1SyncStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1SyncStatus class.
        /// </summary>
        /// <param name="revision">Revision contains information about the
        /// revision the comparison has been performed to</param>
        /// <param name="status">Status is the sync state of the
        /// comparison</param>
        public V1alpha1SyncStatus(V1alpha1ComparedTo comparedTo = default(V1alpha1ComparedTo), string revision = default(string), string status = default(string))
        {
            ComparedTo = comparedTo;
            Revision = revision;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "comparedTo")]
        public V1alpha1ComparedTo ComparedTo { get; set; }

        /// <summary>
        /// Gets or sets revision contains information about the revision the
        /// comparison has been performed to
        /// </summary>
        [JsonProperty(PropertyName = "revision")]
        public string Revision { get; set; }

        /// <summary>
        /// Gets or sets status is the sync state of the comparison
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
