// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// KnownTypeField contains mapping between CRD field and known Kubernetes
    /// type.
    /// This is mainly used for unit conversion in unknown resources (e.g. 0.1
    /// == 100mi)
    /// TODO: Describe the members of this type
    /// </summary>
    public partial class V1alpha1KnownTypeField
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1KnownTypeField class.
        /// </summary>
        public V1alpha1KnownTypeField()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1KnownTypeField class.
        /// </summary>
        public V1alpha1KnownTypeField(string field = default(string), string type = default(string))
        {
            Field = field;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "field")]
        public string Field { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

    }
}
