// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// SyncStrategyApply uses `kubectl apply` to perform the apply
    /// </summary>
    public partial class V1alpha1SyncStrategyApply
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1SyncStrategyApply class.
        /// </summary>
        public V1alpha1SyncStrategyApply()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1SyncStrategyApply class.
        /// </summary>
        /// <param name="force">Force indicates whether or not to supply the
        /// --force flag to `kubectl apply`.
        /// The --force flag deletes and re-create the resource, when PATCH
        /// encounters conflict and has
        /// retried for 5 times.</param>
        public V1alpha1SyncStrategyApply(bool? force = default(bool?))
        {
            Force = force;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets force indicates whether or not to supply the --force
        /// flag to `kubectl apply`.
        /// The --force flag deletes and re-create the resource, when PATCH
        /// encounters conflict and has
        /// retried for 5 times.
        /// </summary>
        [JsonProperty(PropertyName = "force")]
        public bool? Force { get; set; }

    }
}
