// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ApplicationSourceJsonnet holds options specific to applications of type
    /// Jsonnet
    /// </summary>
    public partial class V1alpha1ApplicationSourceJsonnet
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1ApplicationSourceJsonnet
        /// class.
        /// </summary>
        public V1alpha1ApplicationSourceJsonnet()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1ApplicationSourceJsonnet
        /// class.
        /// </summary>
        /// <param name="extVars">ExtVars is a list of Jsonnet External
        /// Variables</param>
        /// <param name="libs">Additional library search dirs</param>
        /// <param name="tlas">TLAS is a list of Jsonnet Top-level
        /// Arguments</param>
        public V1alpha1ApplicationSourceJsonnet(IList<V1alpha1JsonnetVar> extVars = default(IList<V1alpha1JsonnetVar>), IList<string> libs = default(IList<string>), IList<V1alpha1JsonnetVar> tlas = default(IList<V1alpha1JsonnetVar>))
        {
            ExtVars = extVars;
            Libs = libs;
            Tlas = tlas;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets extVars is a list of Jsonnet External Variables
        /// </summary>
        [JsonProperty(PropertyName = "extVars")]
        public IList<V1alpha1JsonnetVar> ExtVars { get; set; }

        /// <summary>
        /// Gets or sets additional library search dirs
        /// </summary>
        [JsonProperty(PropertyName = "libs")]
        public IList<string> Libs { get; set; }

        /// <summary>
        /// Gets or sets TLAS is a list of Jsonnet Top-level Arguments
        /// </summary>
        [JsonProperty(PropertyName = "tlas")]
        public IList<V1alpha1JsonnetVar> Tlas { get; set; }

    }
}
