// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// EventSeries contain information on series of events, i.e. thing that
    /// was/is happening
    /// continuously for some time.
    /// </summary>
    public partial class V1EventSeries
    {
        /// <summary>
        /// Initializes a new instance of the V1EventSeries class.
        /// </summary>
        public V1EventSeries()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1EventSeries class.
        /// </summary>
        /// <param name="count">Number of occurrences in this series up to the
        /// last heartbeat time</param>
        public V1EventSeries(int? count = default(int?), V1MicroTime lastObservedTime = default(V1MicroTime))
        {
            Count = count;
            LastObservedTime = lastObservedTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets number of occurrences in this series up to the last
        /// heartbeat time
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastObservedTime")]
        public V1MicroTime LastObservedTime { get; set; }

    }
}
