// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// VersionMessage represents version of the Argo CD API server
    /// </summary>
    public partial class VersionVersionMessage
    {
        /// <summary>
        /// Initializes a new instance of the VersionVersionMessage class.
        /// </summary>
        public VersionVersionMessage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VersionVersionMessage class.
        /// </summary>
        public VersionVersionMessage(string buildDate = default(string), string compiler = default(string), string gitCommit = default(string), string gitTag = default(string), string gitTreeState = default(string), string goVersion = default(string), string helmVersion = default(string), string jsonnetVersion = default(string), string ksonnetVersion = default(string), string kubectlVersion = default(string), string kustomizeVersion = default(string), string platform = default(string), string version = default(string))
        {
            BuildDate = buildDate;
            Compiler = compiler;
            GitCommit = gitCommit;
            GitTag = gitTag;
            GitTreeState = gitTreeState;
            GoVersion = goVersion;
            HelmVersion = helmVersion;
            JsonnetVersion = jsonnetVersion;
            KsonnetVersion = ksonnetVersion;
            KubectlVersion = kubectlVersion;
            KustomizeVersion = kustomizeVersion;
            Platform = platform;
            Version = version;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BuildDate")]
        public string BuildDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Compiler")]
        public string Compiler { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GitCommit")]
        public string GitCommit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GitTag")]
        public string GitTag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GitTreeState")]
        public string GitTreeState { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GoVersion")]
        public string GoVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HelmVersion")]
        public string HelmVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "JsonnetVersion")]
        public string JsonnetVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KsonnetVersion")]
        public string KsonnetVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KubectlVersion")]
        public string KubectlVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KustomizeVersion")]
        public string KustomizeVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Platform")]
        public string Platform { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Version")]
        public string Version { get; set; }

    }
}
