// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ArgoCD.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Stream result of v1alpha1ApplicationTree
    /// </summary>
    public partial class WatchResourceTreeOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the WatchResourceTreeOKResponse
        /// class.
        /// </summary>
        public WatchResourceTreeOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WatchResourceTreeOKResponse
        /// class.
        /// </summary>
        public WatchResourceTreeOKResponse(RuntimeStreamError error = default(RuntimeStreamError), V1alpha1ApplicationTree result = default(V1alpha1ApplicationTree))
        {
            Error = error;
            Result = result;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public RuntimeStreamError Error { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "result")]
        public V1alpha1ApplicationTree Result { get; set; }

    }
}
