// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Cloud.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// HelmParameter is a parameter that's passed to helm template during
    /// manifest generation
    /// </summary>
    public partial class V1alpha1HelmParameter
    {
        /// <summary>
        /// Initializes a new instance of the V1alpha1HelmParameter class.
        /// </summary>
        public V1alpha1HelmParameter()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the V1alpha1HelmParameter class.
        /// </summary>
        /// <param name="forceString">ForceString determines whether to tell
        /// Helm to interpret booleans and numbers as strings</param>
        /// <param name="name">Name is the name of the Helm parameter</param>
        /// <param name="value">Value is the value for the Helm
        /// parameter</param>
        public V1alpha1HelmParameter(bool? forceString = default(bool?), string name = default(string), string value = default(string))
        {
            ForceString = forceString;
            Name = name;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets forceString determines whether to tell Helm to
        /// interpret booleans and numbers as strings
        /// </summary>
        [JsonProperty(PropertyName = "forceString")]
        public bool? ForceString { get; set; }

        /// <summary>
        /// Gets or sets name is the name of the Helm parameter
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets value is the value for the Helm parameter
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
